services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm start
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
